language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: pQVe2I/WlXZKcU4X9SczuunuxSgku+dOOwOTMljfod8o488CtInxleIHAmwBrn3hhiASP5rafkrtl+ELjlhHIyhFQmybSCS8Nhufy8ldPzpAKTuSi4Ls2dDzBMUJ5wnkVXB5OQv2L36FktIr88UJRpYDbAVxw8Pwc9IkOzOfi7Q/K9IMDW0+KkqiAfUDKE3NEDs7xBN07xqh+Uq2W+Jjpegbd/tI31YryJc09hbrjUi/zecgfZ7OoJUAWIM2WjxzK/CRRBuoggYWa2ft4Bs1gw2nBRXXdyiYsVwUzRQyPmi+LdBTm6GNK6Mn9XqYPhsW/I3yAqm3qafg2o2y+zS1zjvW0yN6EDfOVA4SFj5uboc8BSvqdk64g9nrxwV6rHFX8Mi/BM1uyvs8j6SjLAmCrn6ejfN4gPPmc7lO38sfz0dtxz/dUN7HiLbzrNZTe7deXbZJXpJVgZ20sW53ui51fne8ky0pXnfFD/vrkHmvP5Rxh8DGGe7k8gkU2stGZGfiqJU4ErgGa85oZpIgLGTGauswDDBEavU2oVCcYcUJvKTID0Fqb6x4uRVAI3yUKTz873VvxMyLBJCXr1CqzbrKW4/uA7Djvq53KuuxbTEhLIo2HlnZF8vTtDyD4nTQ3qsOnXiAfOxL+Nen7JF8liRtrOUQtI/30LeG22dj47JXGC0=
