language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: O+gX5PBdYkezh2InjHN3+csWaUJqK39lm+AfxeJOtWJyqB+0SgT7MEALGWHnTF0irhAT5eAFvjgmAOj8CUj4e9Ued104tfVF4FURwHCymTp8/KCsLgTSbNrp3Efci85W4S6DrbWH19GJ4KrNmzZk7SUC4njiuwcObE57xmJb3lpdp2EDnTPXOUQjA+odVv8wHrkNGcS1sWhqUywtwy7CPaxfvNBeKy6TtjU6NYZwABMSu7N3AfQHictLx1HO8cToGFCQhXJlLY4713hFSKmHf9fKiSMUrW1qWOxLnpeQ1isjbOwvdDXdKbcX7fRErPDRCitiOhZXImJTlsN9tSZpJ7CK8DomQzF7N3tH639ZEc1qG4no3sEsk3OdIrlKLKdPbERxGyY6zxnopypevOURgy35gIx/2aXfPQ2GNIh8QfmL7osa/JhQbyhowTtAb1OR/UtKJpKCAAf36doQhJLZUXpoZRPUTrJAZ/amzvnEJ8++vN1u/ZmOlfQE/KFlCVXecFdSVnjUlL6fZzBiSrRd/vQTAsDwW/CmSFFTNsS0NOBrwKHqO62fC07+VvlkM43qXZbgJwi/0+7Br0nsHfwcKatlpsOe8zi+2sQlRKyyhE5J3JS3zwVQXJ3sknHalvndJ146vMrjbywlyC2vb841hjQwx+CcSX12FU4Ku3Ntlsg=
